### PR TITLE
spokane emergency numbers

### PR DESCRIPTION
**Pull request by inandutu**
Added emergency numbers

### CODE REVIEW

**Comment by jefftriplett** [comment]
@Nandutu the copy changes look good but it looks like there were some unrelated files included like some unrelated *.html layout changes. Would you mind posting another PR with just the `_pages/coc.md` update please. I think maybe some of the non-coc.md files might be carry-over from a different branch / older version. Feel free to ping us on Slack and we can walk you through it too if this doesn't make sense.

**Review by jefftriplett — CHANGES_REQUESTED** [review]
Please re-post with just the `_pages/coc.md` copy changes unless other parts of the website need these changes too.

**Comment by inandutu** [comment]
Okay....will review it .
Thanks

Irene Nandutu

**Comment by jefftriplett** [comment]
I pulled the changes over from coc.md to coc.html. Please let me know if I missed something. That's in PR #214.

**Pull request closed without merging**
