### PR TITLE
Updates to remove submission links and references

### PR DESCRIPTION
**Pull request by KatherineMichel**

### CODE REVIEW

**Comment by jefftriplett** [comment]
This is great! My only suggestion would be to replace the `<!--` html comment with `{% comment %}` and `-->` ending comment becomes `{% endcomment %}`. 

The difference between html comments and jekyll comments is that html comments exist when you view source on a page and some search engines will still crawl / index the content even though they shouldn't. If you use jekyll's comment tags (technically, this done by liquid), then they are stripped out of the rendered html page and they won't exist when you view source.

The comment tags are also a good place to document "put this in for the CFP, etc" too which is kind of nice. In theory, would create some _site variables if we wanted to make this a switch in `_config.yml` but that might be over-engineering it :)

If this isn't a quick and easy change, let's just merge it.

**Comment by KatherineMichel** [comment]
No problem. I was wondering about that. I did this quite quickly because I think someone submitted a proposal after the deadline. Something I'm wondering though is if {% comment %} {% endcomment %} can also be used in the .html files or if should leave html commenting as is there?

**Comment by KatherineMichel** [comment]
Nevermind @jefftriplett . It looks like it has been used in the .html files already.

**Review by jefftriplett — APPROVED** [review]
🎉 great work!

**Pull request merged**
