### PR TITLE
Added Anna organizer profile

### PR DESCRIPTION
**Pull request by ossanna16**
Hey! 

I added my  organizer profile. I hope this looks ok. Please let me know if I need to make any changes (especially with the picture, unsure if it's the right size).

Thank you :)

### CODE REVIEW

**Comment by KatherineMichel** [comment]
The pic is too tall/not long enough and distorts the layout when it renders. I cropped it to something close to 400 x 400 and it seems to render ok. Not sure if that is acceptable? @jefftriplett 

anna

**Comment by ossanna16** [comment]
Thanks @KatherineMichel! This looks ok to me. I can also provide a different picture if this one doesn't work.

**Comment by KatherineMichel** [comment]
@ossanna16 I went ahead and did this. I had the photo and wanted to go through the process of making an update to a pull request locally and merging. If the photo needs to be improved, can do that in the future.

**Comment by ossanna16** [comment]
Thanks @KatherineMichel!

**Pull request merged**
