### PR TITLE
Add venue accessibility info

### LINKED ISSUE #103: Venue: Add hotel-specific accessibility info
- [ ] Service animals welcome, there is a park right behind the hotel for walking them. 
- [ ] Step-free access throughout the venue
- [ ] Bathrooms include an ADA stall with grab bars, but not lowered sinks

### PR DESCRIPTION
**Pull request by williln**
If merged, will close #103

### CODE REVIEW

**Review by rebkin05 — APPROVED** [review]
LGTM!

**Comment by KatherineMichel** [comment]
LGTM! Thank you @williln!

**Comment by williln** [comment]
@KatherineMichel Looks like this was closed but not merged?

**Comment by KatherineMichel** [comment]
I think it is fixed now @williln.

**Comment by williln** [comment]
TY!

**Pull request merged**
