### PR TITLE
added orientation blog post and image

### PR DESCRIPTION
**Pull request by kojoidrissa**

### CODE REVIEW

**Comment by KatherineMichel** [comment]
A few of the phrases are blocks of text with not normal styling: Orientation, New or solo attendees, Traditionally underrepresented groups. Assuming they are not supposed to be that way.  
screen shot 2017-07-19 at 2 32 34 am

**Comment by jefftriplett** [comment]
@kojoidrissa you might change some of the `` characters to use`**` instead.

**Comment by kojoidrissa** [comment]
@KatherineMichel the style differences WERE intentional, they just weren't very good. I changed it to use @jefftriplett's suggestion.

**Review by jefftriplett — APPROVED** [review]
LGTM 👍  📢

**Review by KatherineMichel — APPROVED** [review]

**Comment by KatherineMichel** [comment]
Looks much better, smaller headings are not showing as bold on my computer. Perhaps will be bold when deployed. 
screen shot 2017-07-19 at 6 51 44 pm

**Comment by kojoidrissa** [comment]
@jefftriplett & @KatherineMichel, should I merge this, or is someone else supposed to? I'm not sure on the protocol.

**Comment by KatherineMichel** [comment]
@kojoidrissa There is not really a protocol. Anyone who is working on the site who is ready for something to be merged can go ahead and do it. As far as I know, we are using the regular merge option (not squash or rebase).

**Comment by williln** [comment]
@kojoidrissa You are good to merge on your own once it's been approved. Jeff didn't want to merge in case you didn't want the post published yet. (Merging just immediately publishes.)

**Comment by williln** [comment]
(And it's been approved, so you are good to merge when you are ready!)

**Comment by jefftriplett** [comment]
@kojoidrissa my apologies for not making that more clear. Our normal workflow on announcements is to approve it and then letting whomever submitted it merge when they are ready for it. That way we don't accidentally publish it a day too soon or whatnot.

**Comment by kojoidrissa** [comment]
@KatherineMichel you were right, the bolding on the smaller headings showed up once deployed. Not sure why.
screen shot 2017-07-20 at 10 30 38 am

**Comment by KatherineMichel** [comment]
I have seen this happen a few times. Not sure why. Do you know why some markdown styling is only showing when deployed @jefftriplett?

**Comment by jefftriplett** [comment]
@KatherineMichel @kojoidrissa they are **bolded** so I'm not sure why they'd not be before they are deployed. Any reference you could point me to? Also, what were you wanting them to look like? I'm not sure what I'm looking for exactly but it looks good to me on the website itself. Just trying to figure out how to be helpful :)

**Comment by KatherineMichel** [comment]
In the screenshot that I posted, the two smaller headings are not bold when
I run it locally. They only show as bold once deployed, even though the
markdown has not changed.

**Comment by KatherineMichel** [comment]
In the screenshot that I posted, the two smaller headings are not bold when I run it locally. They only show as bold once deployed, even though the markdown has not changed.

**Comment by kojoidrissa** [comment]
@jefftriplett it's the diff b/w the [deployed](https://github.com/djangocon/2017.djangocon.us/pull/224#issuecomment-316740728) and [non-deployed](https://github.com/djangocon/2017.djangocon.us/pull/224#issuecomment-316555376) appearance of the bullets under "What is Orientation?".

Eric Holscher would probably say it's a flaw in Markdown not having a singular standard. 😜

**Pull request merged**
