### PR TITLE
Indicating early bird tickets are sold out

### PR DESCRIPTION
**Pull request by KatherineMichel**
Navbar text became larger when small text was removed. Seems ok. Not sure if this is an adequate update on the ticket page. Am open to other ideas.

### CODE REVIEW

**Review by jefftriplett — APPROVED** [review]
Let's do it live! and see if want to change it.

**Comment by jefftriplett** [comment]
LGTM. cc @williln if she has post-merge thoughts though.

**Comment by jefftriplett** [comment]
@KatherineMichel nice catch on this detail too.

**Comment by williln** [comment]
Thanks for catching this @KatherineMichel! It looks good to me.

**Pull request merged**
