### PR TITLE
Keynote announcement! 

### PR DESCRIPTION
**Pull request by williln**
Might should add a social media photo-- suggestions on which to use?

### CODE REVIEW

**Comment by rebkin05** [comment]
@williln I love the dramatic lecture hall images like:
https://www.flickr.com/photos/144080672@N05/28300184183/in/album-72157672216515946/
https://www.flickr.com/photos/144080672@N05/28810640522/in/album-72157672216515946/
https://www.flickr.com/photos/144080672@N05/28300198393/in/album-72157672216515946/
https://www.flickr.com/photos/144080672@N05/28884410376/in/album-72157672216515946/

**Comment by williln** [comment]
@rebkin05 I used the first one! I should use Pable to add some words and stuff on it though right?

**Comment by rebkin05** [comment]
@williln Yeah, that's what I always do. :)

**Review by jefftriplett — APPROVED** [review]
LGTM 🎉

**Comment by rebkin05** [comment]
🎉 🎉 🎉

**Pull request merged**
