### PR TITLE
Master

### PR DESCRIPTION
**Pull request by brentschneider**
This pull addresses  #78 😌
Places data lists restaurants, bars, and coffee locations around town.  Venue.html displays info from places.yml file. 
**TODO:** Create images for each location. @amfitz once merged lets review your google doc.

### CODE REVIEW

**Comment by jefftriplett** [comment]
Hey @brentschneider, did you make the .scss and css changes or is that an artifact from when you forked the branch? If you didn't change it then it's carry over and I'll remove it. Just wanted to check before I tried to sort it out.

**Comment by brentschneider** [comment]
@jefftriplett it's definitely an artifact that carried over, no changes to `.scss & css`.
Only `_data/places.yml` and `_layouts/venue.html` matter here.

**Comment by jefftriplett** [comment]
I could not get this to merge without an extra 300 commits and some weirdness so I git cherry-picked your changes into: https://github.com/djangocon/2017.djangocon.us/compare/refactor-brentschneider?expand=1

**Comment by jefftriplett** [comment]
@brentschneider thanks for the contribution and feel free to branch off master and push another PR for images once you are ready.

**Pull request closed without merging**
