### PR TITLE
WIP: Edit FAQ page and add to nav bar

### PR DESCRIPTION
**Pull request by williln**
Don't merge until the text is reviewed by @rebkin05, @jefftriplett, @KatherineMichel, please! I just had some free time this morning and wanted to get the HTML done.

### CODE REVIEW

**Comment by KatherineMichel** [comment]
I see a typo to fix (available is spelled wrong). I'm wondering if `<a name="top"></a>` should be in there? If not, I'll remove it and fix the typo.

**Comment by jefftriplett** [comment]
The lint error may be fixed by changing `/venue/#accessibility/` to just `/venue/#accessibility`. I love the rest of it.

**Comment by rebkin05** [comment]
Looks great, @williln!

**Comment by williln** [comment]
@jefftriplett @KatherineMichel The typo is fixed, the errant anchor at the top is fixed, I removed the trailing slash from the accessibility link. 

It looks like the build is still failing on `https://2017.djangocon.us/faq` not being a valid link... is that just because adding the link in the nav bar hasn't been merged? LMK what else I should do!

**Review by KatherineMichel — APPROVED** [review]

**Comment by rebkin05** [comment]
@williln that error happens every time I add a blog post--the link doesn't exist because the page doesn't exist yet.

**Comment by KatherineMichel** [comment]
Thank you, @williln! Yes, the error is gone now because the page exists due to the merge.

**Comment by williln** [comment]
Thank you @KatherineMichel @rebkin05 @jefftriplett!

**Pull request merged**
