### PR TITLE
Replaced CFP on homepage with program announcement

### PR DESCRIPTION
**Pull request by williln**
Addresses #156

### CODE REVIEW

**Comment by williln** [comment]
Would want to update with link to the schedule, once that is released.

**Comment by KatherineMichel** [comment]
It looks good, but I'm wondering if we should leave the two CFP paragraphs commented out because might be used again next year?

**Comment by williln** [comment]
@KatherineMichel I think it's okay to remove them, because the former text will be in the commit history. We should be able to pretty easily see the history of the homepage though GH commits.

**Review by KatherineMichel — APPROVED** [review]

**Comment by KatherineMichel** [comment]
Sounds good. Thank you, @williln!

**Pull request merged**
