### PR TITLE
Adds data for places "Around Spokane"

### PR DESCRIPTION
**Pull request by jefftriplett**
This PR needs data for `places.yml`

### CODE REVIEW

**Comment by amfitz** [comment]
I added the above format to the list I've been working on in google drive for cool stuff in Spokane, https://docs.google.com/document/d/1j2yLqo7cKgBMwHN3IUo1YwybA_bPmPS7BWgP8nBFUD4/edit?usp=sharing

**Comment by jefftriplett** [comment]
@amfitz awesome, thank you. I'd recommend checking out the `venue-places-around-spokane` branch and making your list changes directly in the file to avoid formatting issues that might happen when we try to convert the data. 

For instance, "Location" vs. "location" in the yaml file are treated differently. It's fine to do small edits in your browser too if that's easier.

**Comment by jefftriplett** [comment]
@amfitz I'm happy to help with this too if the branch info didn't make sense or is confusing.

**Comment by amfitz** [comment]
Github noob here. I'll try to play with it on my free time, but if it gets tight on schedule I can ask Brent to do it :)

**Comment by jefftriplett** [comment]
I'm going to defer to @amfitz / @brentschneider to update the data. This PR at least gets the template changes which are needed so all you have to focus on are the `_data/places.yml` updates.

**Comment by brentschneider** [comment]
@amfitz and @jefftriplett sorry for the delay. I've added places in my local version.  Not quite sure how to extend the file to follow the sponsors.yml category convention, think I'll send a merge request with what I got  .. we can iterate another version afterwards.

**Comment by jefftriplett** [comment]
@brentschneider feel free to push a branch or send a gist of what you have if you aren't sure. I'm happy to review / help with it.

**Pull request merged**
